export enum ErrorCode {
  MYSQL_DATABASE_ERROR = "MYSQL_DATABASE_ERROR",
  GOOGLE_OAUTH_ERROR = "GOOGLE_OAUTH_ERROR",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_CATEGORY_FORMAT = "INVALID_CATEGORY_FORMAT",
  MISS_REQUIRED_FELIDS = "MISS_REQUIRED_FELIDS",
  FORBIDDEN = "FORBIDDEN",
}

export const ErrorCodeMapToStatus = {
  [ErrorCode.MYSQL_DATABASE_ERROR]: 500,
  [ErrorCode.GOOGLE_OAUTH_ERROR]: 500,
  [ErrorCode.INVALID_EMAIL]: 400,
  [ErrorCode.MISS_REQUIRED_FELIDS]: 400,
  [ErrorCode.INVALID_CATEGORY_FORMAT]: 400,
  [ErrorCode.FORBIDDEN]: 403,
};
